package view;

import controller.Controller;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import model.ChuyenBay;
import model.Ve;

/**
 *
 * @author PC
 */
public class GiaoDienDSVe extends javax.swing.JFrame {
    
    private  ArrayList<JButton> listGhe= new ArrayList<JButton>();
    public GiaoDienDSVe() {      

        initComponents();
        controller.Controller.dsGheChon.removeAll(controller.Controller.dsGheChon);    
        ArrayList<String> mapGhe= new ArrayList<String>();
        myTitle.setText("Sơ Đồ Vé Chuyến Bay "+controller.Controller.cb.getMaChuyenBay()); 
        if(Controller.cb.getTrangThai()==ChuyenBay.HUYCHUYEN ||Controller.cb.getTrangThai()==ChuyenBay.HOANTAT )
            jButtonHuyVe.setVisible(false);
        int soGhe= controller.Controller.cb.getSoGhe();
        thongTinVe.setVisible(false);
        mapGhe.add("");
        for (int i = 0; i < soGhe; i++) {
            mapGhe.add("0");
        }

        for (Ve Ve :controller.Controller.cb.getArrayListVe() ) {
            mapGhe.set(Integer.parseInt(Ve.getMaGhe()),Ve.getMaGhe());
        }
	int chiso=1;
        int kichthuoc=80;
         
         for(int i=0; ;i=i+kichthuoc+10){
	  for(int j=1;j<=6;j++)
          {
	  	 JButton jButton1 =new JButton();
                 jButton1.setBounds(50+(j-1)*(kichthuoc+10)+100*(j>3?1:0),10+i,kichthuoc,kichthuoc);
                 jPanel1.add(jButton1);
                 jButton1.setText(String.valueOf(chiso));
                 if( ! mapGhe.get(chiso).equals("0")) {
                    jButton1.setBackground(Color.RED);
                   if(Controller.tk.getLoaiTaiKhoan().equals("guest"))
                       jButton1.setEnabled(false);
                 }
                 else{
                    if(!Controller.tk.getLoaiTaiKhoan().equals("guest"))
                       jButton1.setEnabled(false);
                 }
                 
                 
                 jButton1.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                         chonGhe(evt,jButton1);
            }});
                     listGhe.add(jButton1);
		if(chiso++==soGhe) {
                              return;
                       }
	   } 
	}
           
      
    }

    private void chonGhe(java.awt.event.ActionEvent evt,JButton btn) {
        if(Controller.tk.getLoaiTaiKhoan().equals("guest"))
        {
                for (String st :controller.Controller.dsGheChon) {
                   if(btn.getText().equals(st)){
                   btn.setBackground(new java.awt.Color(240, 240, 240));
                   controller.Controller.dsGheChon.remove(st);
                   return;
                   }
               }
               if(controller.Controller.dsGheChon.size()+1<controller.Controller.soLuongVeChon){
                       btn.setBackground(Color.GREEN);
                       controller.Controller.dsGheChon.add(btn.getText());
               }
               else{
                   controller.Controller.dsGheChon.add(btn.getText());
                   controller.Controller.dsVeChon.removeAll(controller.Controller.dsVeChon);
                   new GiaoDienThongTinVe().setVisible(true);    
                   this.dispose();
           }
        
        }else{
              thongTinVe.setVisible(true);
            for (Ve ve: controller.Controller.cb.getArrayListVe()) {
                if(btn.getText().equals(ve.getMaGhe())){
                   jLabelmaGhe.setText(ve.getMaGhe());
                   lbTenKhachHang.setText(ve.getTenHanhKhach());
                   lbSDT.setText(ve.getsDT());
                    return;
                }
                    
            }
        
        
        }
       
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        myTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        thongTinVe = new javax.swing.JPanel();
        lbVe = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonHuyVe = new javax.swing.JButton();
        jLabelmaGhe = new javax.swing.JLabel();
        lbTenKhachHang = new javax.swing.JTextField();
        lbSDT = new javax.swing.JTextField();
        chuThich = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SƠ ĐỒ VÉ");
        setLocation(new java.awt.Point(0, 0));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        myTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myTitle.setText("SƠ ĐỒ VÉ");

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 9980));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9980, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel1);

        thongTinVe.setBackground(new java.awt.Color(204, 204, 255));

        lbVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbVe.setText("Vé");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel7.setText("Tên Khách Hàng");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel9.setText("SDT");

        jButtonHuyVe.setBackground(new java.awt.Color(255, 102, 102));
        jButtonHuyVe.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonHuyVe.setText("Hủy Vé");
        jButtonHuyVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyVeActionPerformed(evt);
            }
        });

        jLabelmaGhe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbTenKhachHang.setEnabled(false);
        lbTenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTenKhachHangActionPerformed(evt);
            }
        });

        lbSDT.setEnabled(false);

        javax.swing.GroupLayout thongTinVeLayout = new javax.swing.GroupLayout(thongTinVe);
        thongTinVe.setLayout(thongTinVeLayout);
        thongTinVeLayout.setHorizontalGroup(
            thongTinVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongTinVeLayout.createSequentialGroup()
                .addGroup(thongTinVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(thongTinVeLayout.createSequentialGroup()
                        .addGroup(thongTinVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(thongTinVeLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(lbVe, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelmaGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(thongTinVeLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButtonHuyVe))
                            .addGroup(thongTinVeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(thongTinVeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(thongTinVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTenKhachHang)
                            .addComponent(lbSDT))))
                .addContainerGap())
        );
        thongTinVeLayout.setVerticalGroup(
            thongTinVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongTinVeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thongTinVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbVe, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(jLabelmaGhe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jButtonHuyVe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chuThich.setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));

        jButton3.setBackground(new java.awt.Color(0, 255, 51));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel4.setText("Đã Chọn");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel5.setText("Còn Trống");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel6.setText("Đang Chọn");

        javax.swing.GroupLayout chuThichLayout = new javax.swing.GroupLayout(chuThich);
        chuThich.setLayout(chuThichLayout);
        chuThichLayout.setHorizontalGroup(
            chuThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chuThichLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(chuThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(chuThichLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(chuThichLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chuThichLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        chuThichLayout.setVerticalGroup(
            chuThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chuThichLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(chuThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chuThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chuThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(405, 405, 405)
                        .addComponent(myTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chuThich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(thongTinVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back)
                    .addComponent(myTitle, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(chuThich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(thongTinVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        
        if(controller.Controller.tk.getLoaiTaiKhoan().equals("guest")){
               new GiaoDienChonChuyenBay().setVisible(true);
        }
        else{
            new GiaoDienChuyenBay().setVisible(true);       
        }
       this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jButtonHuyVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyVeActionPerformed
        // TODO add your handling code here:
         int confirmed = JOptionPane.showConfirmDialog(null,
                        "Xác Nhận Hủy Vé ?", "Xác nhận",JOptionPane.YES_NO_OPTION);

         if (confirmed == JOptionPane.YES_OPTION) {
                 connection.DeleteData.deleteVe(controller.Controller.cb.getMaChuyenBay(),jLabelmaGhe.getText());   
                 listGhe.get(Integer.parseInt(jLabelmaGhe.getText())-1).setEnabled(false);
                 listGhe.get(Integer.parseInt(jLabelmaGhe.getText())-1).setBackground(new java.awt.Color(240, 240, 240));
                 if(controller.Controller.cb.getTrangThai()==ChuyenBay.HETVE)
                          connection.UpdateData.capNhatConVe(controller.Controller.cb.getMaChuyenBay());
            }
    }//GEN-LAST:event_jButtonHuyVeActionPerformed

    private void lbTenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTenKhachHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDSVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDSVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDSVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDSVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienDSVe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JPanel chuThich;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonHuyVe;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelmaGhe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lbSDT;
    private javax.swing.JTextField lbTenKhachHang;
    private javax.swing.JLabel lbVe;
    private javax.swing.JLabel myTitle;
    private javax.swing.JPanel thongTinVe;
    // End of variables declaration//GEN-END:variables
}
