/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import connection.LoadData;
import java.awt.Color;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChuyenBay;
import model.DuongBay;

/**
 *
 * @author PC
 */
public class GiaoDienChuyenBay extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChuyenBay
     */
    private DefaultTableModel table;
    private int cheDo;

    public GiaoDienChuyenBay() {
        initComponents();
        table = (DefaultTableModel) jTable1.getModel();
        cheDo=0;
        showData();
        jTable1.setDefaultEditor(Object.class, null);;
        jTable1.setSelectionBackground(Color.RED);
        jTable1.setSelectionMode(0);
        for (model.MayBay mb : controller.Controller.arrayListMayBay) 
            jComboBoxSHMB.addItem(mb.getSHMB().trim() );
        for (model.DuongBay db : controller.Controller.arrayListDuongBay) 
            jComboBoxDuongBay.addItem(db.getMaSanBayDi()+ "->"+ db.getMasanBayDen() );
        
        
        
    }
    private void showData(){
        
        new LoadData();
        table.setRowCount(0);
        for (ChuyenBay cb: controller.Controller.arrayListChuyenBay) {
           if(cb.getTrangThai()== this.cheDo)
            table.addRow(new Object[]{cb.getMaChuyenBay(),cb.getSHMB(),cb.getDuongBay().getMaSanBayDi()+"->"+cb.getDuongBay().getMasanBayDen(),cb.getNgayBay()+" " +cb.getGioBay()});       
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonADD = new javax.swing.JButton();
        jButtonHC = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jButtonCann = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMaCB = new javax.swing.JTextField();
        jComboBoxSHMB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jDateChooserNgayBay = new com.toedter.calendar.JDateChooser();
        jComboBox_GioDi1 = new javax.swing.JComboBox<>();
        jComboBox_PhutDi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxDuongBay = new javax.swing.JComboBox<>();
        jButtonDSVe = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        baoloi = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ CHUYẾN BAY");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jButtonADD.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonADD.setText("Thêm");
        jButtonADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDActionPerformed(evt);
            }
        });

        jButtonHC.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonHC.setText("Hủy Chuyến");
        jButtonHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHCActionPerformed(evt);
            }
        });

        jButtonEdit.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonEdit.setText("Sửa");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jLabel1.setText("SHMB");

        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonSave.setText("Lưu");
        jButtonSave.setEnabled(false);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCann.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonCann.setText("Hủy");
        jButtonCann.setEnabled(false);
        jButtonCann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCannActionPerformed(evt);
            }
        });

        jLabel2.setText("Giờ Bay");

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel4.setText("Mã Chuyến Bay");

        jTextFieldMaCB.setEnabled(false);
        jTextFieldMaCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldMaCBMouseClicked(evt);
            }
        });

        jComboBoxSHMB.setEnabled(false);
        jComboBoxSHMB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxSHMBMouseClicked(evt);
            }
        });

        jLabel5.setText("Ngày Bay");

        jDateChooserNgayBay.setDateFormatString("dd/MM/yyyy");
        jDateChooserNgayBay.setEnabled(false);
        jDateChooserNgayBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooserNgayBayMouseClicked(evt);
            }
        });

        jComboBox_GioDi1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jComboBox_GioDi1.setEnabled(false);

        jComboBox_PhutDi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "" }));
        jComboBox_PhutDi.setEnabled(false);
        jComboBox_PhutDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_PhutDiActionPerformed(evt);
            }
        });

        jLabel6.setText(":");

        jLabel3.setText("Đường Bay");

        jComboBoxDuongBay.setEnabled(false);
        jComboBoxDuongBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxDuongBayMouseClicked(evt);
            }
        });
        jComboBoxDuongBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDuongBayActionPerformed(evt);
            }
        });

        jButtonDSVe.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonDSVe.setText("DSVe");
        jButtonDSVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDSVeActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Chuyến Bay", "SHMB", "Đường Bay", "Thời Gian"
            }
        ));
        jTable1.setRowHeight(34);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        baoloi.setForeground(new java.awt.Color(255, 0, 0));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Còn Vé");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Hết Vé");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Hủy Chuyến");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Hoàn Tất");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(jComboBox_GioDi1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_PhutDi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jDateChooserNgayBay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxDuongBay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(57, 57, 57)
                            .addComponent(jComboBoxSHMB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldMaCB))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(55, 55, 55)
                            .addComponent(jButtonCann))
                        .addComponent(baoloi, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonDSVe)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonADD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonEdit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonHC))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonADD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDSVe, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMaCB)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSHMB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jComboBoxDuongBay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooserNgayBay, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jComboBox_PhutDi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox_GioDi1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCann, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(baoloi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(true);
        this.cheDo=ChuyenBay.CONVE;
        showData();
        jTable1.setEnabled(false);
        jTable1.clearSelection();
        jTextFieldMaCB.setText("");
        jTextFieldMaCB.setEnabled(true);
        jComboBoxSHMB.setEnabled(true);
        jComboBoxSHMB.setSelectedIndex(0);
        jComboBoxDuongBay.setEnabled(true);
        jDateChooserNgayBay.setEnabled(true);
        jComboBox_GioDi1.setEnabled(true);
        jComboBox_PhutDi.setEnabled(true);
        jButtonSave.setEnabled(true);
        jButtonCann.setEnabled(true);
        String date = new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime());
     
         try {
            java.util.Date  datenow = new SimpleDateFormat("dd/MM/yyyy").parse(date);
             jDateChooserNgayBay.setDate(datenow);
         } catch (ParseException ex) {
             Logger.getLogger(GiaoDienChuyenBay.class.getName()).log(Level.SEVERE, null, ex);
         }
      
    }//GEN-LAST:event_jButtonADDActionPerformed

    private void jButtonHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHCActionPerformed
        baoloi.setText("");
        if(jTable1.getSelectedRow()==-1){
            baoloi.setText("Vui lòng chọn chuyến bay");}
        else
        { 
          int confirmed = JOptionPane.showConfirmDialog(null,
                        "Xác Nhận Xóa Chuyến Bay?", "Xác nhận",JOptionPane.YES_NO_OPTION);

                if (confirmed == JOptionPane.YES_OPTION) {
                     connection.UpdateData.huyChuyenBay((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
                     showData();
                } 
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButtonHCActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new GiaoDienQuanLy().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox_PhutDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_PhutDiActionPerformed
        baoloi.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_PhutDiActionPerformed

    private void jComboBoxDuongBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDuongBayActionPerformed
        baoloi.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDuongBayActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        baoloi.setText("");
       jTextFieldMaCB.setText(jTextFieldMaCB.getText().toUpperCase());
        
        if(jTextFieldMaCB.getText().equals("")){
            baoloi.setText("Vui lòng điền đầy đủ thông tin chuyến bay");
            return;
        }
        Date datenow = Calendar.getInstance().getTime();
        Time myTime=new Time(
                                Integer.parseInt(jComboBox_GioDi1.getSelectedItem().toString()),
                                Integer.parseInt(jComboBox_PhutDi.getSelectedItem().toString()),
                            0);
        if((jDateChooserNgayBay.getDate().getTime()+myTime.getTime()+7*3600000)-datenow.getTime() < 24*3600000){
            baoloi.setText("Chuyen Bay Phải mở trước khi bay 1 ngày");
            return;
        }
        java.sql.Date myDate=new java.sql.Date(jDateChooserNgayBay.getDate().getTime());
        DuongBay myDuongBay= controller.Controller.arrayListDuongBay.get(jComboBoxDuongBay.getSelectedIndex());
                  
            ChuyenBay cb=new ChuyenBay(jTextFieldMaCB.getText(),jComboBoxSHMB.getSelectedItem().toString(),
                   myDuongBay, 
                   myDate, myTime,ChuyenBay.CONVE);
          int row = jTable1.getSelectedRow();
            if (jTable1.getSelectedRow()==-1)
            {
                for(ChuyenBay chbay: controller.Controller.arrayListChuyenBay) {
                        if(cb.getMaChuyenBay().equals(chbay.getMaChuyenBay())) { 
                            baoloi.setText("Mã Chuyến Bay đã tồn tại ");
                             return;
                          }
                     if( (cb.getSHMB().equals(chbay.getSHMB()) ||(cb.getDuongBay().equals(chbay.getDuongBay())))
                       &&
                         (Math.abs(chbay.getCBTime().getTime()-cb.getCBTime().getTime() )< 1800000)){
                            baoloi.setText("Không Thể Thêm CB Vao Thoi Gian Nay");
                            return;
                    }
                }
                connection.InsertData.insertChuyenBay(cb);
             
            }
            else{
                for(ChuyenBay chbay: controller.Controller.arrayListChuyenBay) 
                     if( (!cb.getMaChuyenBay().equals(chbay.getMaChuyenBay())) 
                       &&  (Math.abs(chbay.getCBTime().getTime()-cb.getCBTime().getTime() )< 1800000)){
                            baoloi.setText("Không Thể Sửa CB Vao Thoi Gian Nay");
                            return;
                    }
                
                connection.UpdateData.updateChuyenBay(cb);
            }
            showData();
            jTable1.setEnabled(true);
            jTextFieldMaCB.setEnabled(false);
            jComboBoxSHMB.setEnabled(false);
            jComboBoxSHMB.setSelectedIndex(0);
            jComboBoxDuongBay.setEnabled(false);
            jDateChooserNgayBay.setEnabled(false);
            jComboBox_GioDi1.setEnabled(false);
            jComboBox_PhutDi.setEnabled(false);
            jButtonSave.setEnabled(false);
            jButtonCann.setEnabled(false);
            jButtonEdit.setEnabled(true);
            jButtonHC.setEnabled(true);
            jTable1.getSelectionModel().setSelectionInterval(row,row);
        
        
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonDSVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDSVeActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow() == -1){
            baoloi.setText("Vui lòng chọn chuyến bay.");
            return;
        }
        for (ChuyenBay cbb : controller.Controller.arrayListChuyenBay) {
            if(cbb.getMaChuyenBay().equals(jTable1.getValueAt(jTable1.getSelectedRow(),0))) {
                controller.Controller.cb =cbb;
                break;
            }  
        }
        new GiaoDienDSVe().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonDSVeActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
         baoloi.setText("");// TODO add your handling code here:
        if(jTable1.getSelectedRow() == -1)
             baoloi.setText("Vui lòng chọn chuyến bay.");
        else {
            jDateChooserNgayBay.setEnabled(true);
            jComboBox_GioDi1.setEnabled(true);
            jComboBox_PhutDi.setEnabled(true);
            jButtonSave.setEnabled(true);
            jButtonCann.setEnabled(true);
            
        }
       // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        baoloi.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jTextFieldMaCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldMaCBMouseClicked
        baoloi.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaCBMouseClicked

    private void jComboBoxSHMBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxSHMBMouseClicked
        baoloi.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSHMBMouseClicked

    private void jComboBoxDuongBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxDuongBayMouseClicked
        baoloi.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDuongBayMouseClicked

    private void jDateChooserNgayBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooserNgayBayMouseClicked
        baoloi.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserNgayBayMouseClicked

    private void jButtonCannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCannActionPerformed
         baoloi.setText("");// TODO add your handling code here:
         jTable1.setEnabled(true);
         jTextFieldMaCB.setEnabled(false);
        jComboBoxSHMB.setEnabled(false);
        jComboBoxSHMB.setSelectedIndex(0);
        jComboBoxDuongBay.setEnabled(false);
        jDateChooserNgayBay.setEnabled(false);
        jComboBox_GioDi1.setEnabled(false);
        jComboBox_PhutDi.setEnabled(false);
        jButtonSave.setEnabled(false);
        jButtonCann.setEnabled(false);
        jButtonEdit.setEnabled(true);
        jButtonHC.setEnabled(true);
    }//GEN-LAST:event_jButtonCannActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        this.cheDo=ChuyenBay.CONVE;
        showData();
        jButtonEdit.setEnabled(true);
        jButtonHC.setEnabled(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        this.cheDo=ChuyenBay.HETVE;
        showData();
        jButtonEdit.setEnabled(true);
        jButtonHC.setEnabled(true);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        this.cheDo=ChuyenBay.HUYCHUYEN;
        showData();
        jButtonEdit.setEnabled(false);
        jButtonHC.setEnabled(false);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        this.cheDo=ChuyenBay.HOANTAT;
        showData();
        jButtonEdit.setEnabled(false);
        jButtonHC.setEnabled(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        baoloi.setText("");// TODO add your handling code here:
        int row= jTable1.getSelectedRow();
        jTextFieldMaCB.setText((String) jTable1.getValueAt(row,0));
        jComboBoxSHMB.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 1));
        jComboBoxDuongBay.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 2));
        String datebay = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
        jComboBox_GioDi1.setSelectedItem(datebay.substring(11, 13));   
        jComboBox_PhutDi.setSelectedItem(datebay.substring(14, 16));
        
        datebay=datebay.substring(8,10)+"/"+datebay.substring(5,7)+"/"+datebay.substring(0,4);
     
         try {
            java.util.Date  datetmp = new SimpleDateFormat("dd/MM/yyyy").parse(datebay);
             jDateChooserNgayBay.setDate(datetmp);
         } catch (ParseException ex) {
             Logger.getLogger(GiaoDienChuyenBay.class.getName()).log(Level.SEVERE, null, ex);
         }
         
         
         
    }//GEN-LAST:event_jTable1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChuyenBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChuyenBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChuyenBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChuyenBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChuyenBay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baoloi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonADD;
    private javax.swing.JButton jButtonCann;
    private javax.swing.JButton jButtonDSVe;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHC;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxDuongBay;
    private javax.swing.JComboBox<String> jComboBoxSHMB;
    private javax.swing.JComboBox<String> jComboBox_GioDi1;
    private javax.swing.JComboBox<String> jComboBox_PhutDi;
    private com.toedter.calendar.JDateChooser jDateChooserNgayBay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldMaCB;
    // End of variables declaration//GEN-END:variables

}
