/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author PC
 */
public class GiaoDienQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienNhanVien
     */
    public GiaoDienQuanLy() {
        initComponents();
         System.out.println(controller.Controller.tk.getLoaiTaiKhoan());
        if(controller.Controller.tk.getLoaiTaiKhoan().equals("staff")){
              btnNhanVien.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNhanVien = new javax.swing.JButton();
        btnDuongBay = new javax.swing.JButton();
        btnSanBay = new javax.swing.JButton();
        btnChuyenBay = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnMayBay = new javax.swing.JButton();
        btnTimChuyen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME");
        setLocation(new java.awt.Point(0, 0));

        btnNhanVien.setBackground(new java.awt.Color(0, 153, 255));
        btnNhanVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/—Pngtree—employee icon vector illustration in_4257910.png"))); // NOI18N
        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnDuongBay.setBackground(new java.awt.Color(255, 153, 51));
        btnDuongBay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDuongBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/_Pngtree_route_flat_multi_color_icon_3777261-removebg-preview.png"))); // NOI18N
        btnDuongBay.setText("Đươờng Bay");
        btnDuongBay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDuongBay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDuongBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuongBayActionPerformed(evt);
            }
        });

        btnSanBay.setBackground(new java.awt.Color(51, 51, 255));
        btnSanBay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSanBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_runway_52px.png"))); // NOI18N
        btnSanBay.setText("Sân Bay");
        btnSanBay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSanBay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSanBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanBayActionPerformed(evt);
            }
        });

        btnChuyenBay.setBackground(new java.awt.Color(51, 255, 51));
        btnChuyenBay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChuyenBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kisspng-airplane-flight-computer-icons-airline-ticket-ticket-5abcf231227d01.6528235915223322091413.png"))); // NOI18N
        btnChuyenBay.setText("Chuyến Bay");
        btnChuyenBay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenBay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyenBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenBayActionPerformed(evt);
            }
        });

        btnKhachHang.setBackground(new java.awt.Color(255, 153, 204));
        btnKhachHang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_customer_50px_2.png"))); // NOI18N
        btnKhachHang.setText("Khách Hàng");
        btnKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnThongKe.setBackground(new java.awt.Color(255, 0, 51));
        btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/56805.png"))); // NOI18N
        btnThongKe.setText("Thoát");
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongKeMouseClicked(evt);
            }
        });
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnMayBay.setBackground(new java.awt.Color(0, 204, 204));
        btnMayBay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMayBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image-removebg-preview (1)w.png"))); // NOI18N
        btnMayBay.setText("Máy Bay");
        btnMayBay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMayBay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayBayActionPerformed(evt);
            }
        });

        btnTimChuyen.setBackground(new java.awt.Color(255, 255, 102));
        btnTimChuyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTimChuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7d74215fae51a37bb027798dedc16812-removebg-preview.png"))); // NOI18N
        btnTimChuyen.setText("Tìm Vé");
        btnTimChuyen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTimChuyen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTimChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimChuyenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChuyenBay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSanBay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMayBay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimChuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDuongBay)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTimChuyen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChuyenBay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSanBay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMayBay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDuongBay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        new GiaoDienNhanVien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnDuongBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuongBayActionPerformed
        // TODO add your handling code here:
         new GiaoDienDuongBay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDuongBayActionPerformed

    private void btnSanBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanBayActionPerformed
        // TODO add your handling code here:
        new GiaoDienSanBay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSanBayActionPerformed

    private void btnChuyenBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenBayActionPerformed
        // TODO add your handling code here:
         new GiaoDienChuyenBay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnChuyenBayActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
         new GiaoDienKhachHang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayBayActionPerformed
        // TODO add your handling code here:
        new GiaoDienMayBay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMayBayActionPerformed

    private void btnTimChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimChuyenActionPerformed
        
        new GiaoDienTimChuyenBay().setVisible(true);
           this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimChuyenActionPerformed

    private void btnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseClicked
        // TODO add your handling code here:
        new DangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThongKeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowns".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenBay;
    private javax.swing.JButton btnDuongBay;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnMayBay;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnSanBay;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTimChuyen;
    // End of variables declaration//GEN-END:variables
}
